"""Added hashed password column in users

Revision ID: a66356c8eb3f
Revises: 62604b64e705
Create Date: 2024-05-07 20:18:30.139895

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a66356c8eb3f"
down_revision: Union[str, None] = "62604b64e705"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("hashed_password", sa.String(), nullable=False))
    op.create_unique_constraint("users_id_unique", "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_id_unique", "users", type_="unique")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###
